lib/quest_web/router.ex
defmodule QuestWeb.Router do
  use QuestWeb, :router
  use Coherence.Router
  use ExAdmin.Router
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session  # Add this
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true  # Add this
  end

  pipeline :admin_routes do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true  # Add this
    plug QuestWeb.Plug.Admin
  end

  # Add this block
  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  # Add this block
  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", QuestWeb do
    pipe_through :browser
    get "/", PageController, :index

    # Add public routes below
  end

  scope "/admin", ExAdmin do
    pipe_through :admin_routes
    admin_routes()
  end

  # scope "/admin", QuestWeb.Admin, as: :admin do
  #   pipe_through :admin_routes
  #   resources "/topics", TopicController
  # end

  scope "/", QuestWeb do
    pipe_through :protected
    resources "/profile", ProfileController, singleton: true
    put "/", PageController, :setup_account, as: :setup_account
    resources "/topics", TopicController, only: [:index, :show]
    # Add protected routes below
  end

  if Mix.env == :dev do
    scope "/dev" do
      pipe_through [:browser]
      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end
end

lib/quest_web/templates/page/index.html.eex
<%= if @current_user do %>
  <%= if @current_user.setup_done do %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-2">
          Feed
          <hr />
          <%= for user_topic <- @topics do %>
            <p> <%= user_topic.topic.name %></p>
          <% end %>
        </div>
        <div class="col"></div>
        <div class="col"></div>
      </div>
    </div>
  <% else %>
    <script>alert('helloing');</script>
    <div class="modal-backdrop setup-box">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Select topics of your interest:</h5>
          </div>
          <div class="modal-body">
            Select your topics:
            <%= form_for @changeset, setup_account_path(@conn, :setup_account), fn f -> %>
              <%= for {topic_chunk, row_index} <- Enum.with_index(@topics) do %>
                <div class="row" style="margin-bottom: 20px; margin-top: 20px;">
                  <%= for {topic, index} <- Enum.with_index(topic_chunk) do %>
                    <div class="col-4">
                      <img src="<%= Quest.Avatar.url({topic.avatar, topic}, :thumb)%>" alt="" />
                      <%= if user_topic = Quest.Coherence.User.has_topic(@current_user, topic.id) do %>
                        <input name="user[user_topics][<%= topic_index(row_index, index) %>][id]" type="hidden" value="<%= user_topic.id %>">
                        <input type="hidden" name="user[user_topics][<%= topic_index(row_index, index) %>][topic_id]" value="<%= topic.id %>"/>
                        <input name="user[user_topics][<%= topic_index(row_index, index) %>][delete]" type="hidden" value="true">
                        <input name="user[user_topics][<%= topic_index(row_index, index) %>][delete]" type="checkbox" value="false" checked="checked">
                      <% else %>
                        <input type="checkbox" name="user[user_topics][<%= topic_index(row_index, index) %>][topic_id]" value="<%= topic.id %>"/>
                      <% end %>
                      <%= topic.name %>
                    </div>
                  <% end %>
                </div>
              <% end %>
              <div class="d-flex align-items-end flex-column">
                <%= submit "Submit", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="justify-content-center align-items-center d-flex full-width">
    <div class="card">
      <div class="card-body">
        <div class="card-logo justify-content-center d-flex">Quest</div>
        Find the best answers to the best questions in the world.
        <br />
        <br />
        <div class="d-flex flex-row">
          <%= link "Login", to: session_path(@conn, :new), class: "btn btn-primary half-width m-r-15" %>
          <%= link "Signup", to: registration_path(@conn, :new), class: "btn btn-primary half-width m-l-15" %>
          <%# <button class="btn btn-primary half-width m-r-15">Login</button> %>
          <%# <button class="btn btn-primary half-width m-l-15">Signup</button> %>
        </div>
      </div>
    </div>
  </div>
<% end %>

lib/quest_web/templates/page/setup_account.html.eex
<%= case @step do %>
<% 1 -> %>
  <div class="container-fluid">
    test
  </div>
<% 2 -> %>
  Test
<% end %>